apiVersion: apps/v1
kind: Deployment
metadata: 
  {{ $fullname := printf "%s%s" .Chart.Name .Values.image.number | trunc 63 | trimSuffix "-" }}
  {{ $project := printf "%s-%s%s" .Values.Author .Values.image.name .Values.image.number | trunc 63 | trimSuffix "-" }}
  {{ $namespace := printf "%s%s" .Values.namespace.name .Values.namespace.number | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  namespace: {{ $namespace }}
  labels:
    chart: {{ $fullname }}
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ $project }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
          - containerPort: {{ .Values.image.port }}
            name: http
        